#!/bin/sh

xcodebuild -project DeLorean.xcodeproj -scheme DeLorean -configuration Test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X' -enableCodeCoverage YES build-for-testing test-without-building | xcpretty
# slather coverage
